/** @type {import('jest').Config} */
module.exports = {
  preset: 'jest-expo',
  setupFiles: ['./jest.setup.js'],
  moduleNameMapper: {
    '^@mycircle/shared$': '<rootDir>/packages/shared/src',
    '^@mycircle/weather$': '<rootDir>/packages/weather/src',
    '^@mycircle/stocks$': '<rootDir>/packages/stocks/src',
    '^@mycircle/podcasts$': '<rootDir>/packages/podcasts/src',
    '^@mycircle/ai-assistant$': '<rootDir>/packages/ai-assistant/src',
    '^@mycircle/bible-reader$': '<rootDir>/packages/bible-reader/src',
    '^@mycircle/worship-songs$': '<rootDir>/packages/worship-songs/src',
    '^@mycircle/notebook$': '<rootDir>/packages/notebook/src',
    '^@mycircle/baby-tracker$': '<rootDir>/packages/baby-tracker/src',
    '^@mycircle/child-development$': '<rootDir>/packages/child-development/src',
    '^@mycircle/flashcards$': '<rootDir>/packages/flashcards/src',
    '^@mycircle/daily-log$': '<rootDir>/packages/daily-log/src',
    '^@mycircle/city-search$': '<rootDir>/packages/city-search/src',
    '^@mycircle/radio-station$': '<rootDir>/packages/radio-station/src',
    '^@mycircle/poll-system$': '<rootDir>/packages/poll-system/src',
    '^@mycircle/trip-planner$': '<rootDir>/packages/trip-planner/src',
    '^@mycircle/digital-library$': '<rootDir>/packages/digital-library/src',
    '^@mycircle/family-games$': '<rootDir>/packages/family-games/src',
    '^@mycircle/doc-scanner$': '<rootDir>/packages/doc-scanner/src',
    '^@mycircle/hiking-map$': '<rootDir>/packages/hiking-map/src',
    '^@mycircle/ai-interviewer$': '<rootDir>/packages/ai-interviewer/src',
    '^@mycircle/anniversary$': '<rootDir>/packages/anniversary/src',
    '^@mycircle/cloud-files$': '<rootDir>/packages/cloud-files/src',
    '^@mycircle/immigration-tracker$': '<rootDir>/packages/immigration-tracker/src',
    '^@mycircle/model-benchmark$': '<rootDir>/packages/model-benchmark/src',
    '^@mycircle/deal-finder$': '<rootDir>/packages/deal-finder/src',
    '^@mycircle/hsa-expenses$': '<rootDir>/packages/hsa-expenses/src',
    '^@mycircle/resume-tailor$': '<rootDir>/packages/resume-tailor/src',
    '^@mycircle/transit-tracker$': '<rootDir>/packages/transit-tracker/src',
    '^@mycircle/travel-map$': '<rootDir>/packages/travel-map/src',
    '^@mycircle/web-crawler$': '<rootDir>/packages/web-crawler/src',
    '^@react-native-firebase/app$': '<rootDir>/__mocks__/@react-native-firebase/app.js',
    '^@react-native-firebase/auth$': '<rootDir>/__mocks__/@react-native-firebase/auth.js',
    '^@react-native-firebase/firestore$': '<rootDir>/__mocks__/@react-native-firebase/firestore.js',
    '^@react-native-firebase/messaging$': '<rootDir>/__mocks__/@react-native-firebase/messaging.js',
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@sentry/react-native|native-base|react-native-svg|nativewind|react-native-reanimated|react-native-gesture-handler|react-native-screens|react-native-safe-area-context|@shopify/react-native-skia|react-native-gifted-charts)',
  ],
  collectCoverageFrom: [
    'packages/*/src/**/*.{ts,tsx}',
    'src/**/*.{ts,tsx}',
    'app/**/*.{ts,tsx}',
    '!**/*.d.ts',
    '!**/index.ts',
    '!**/types.ts',
    '!**/node_modules/**',
  ],
  coverageThreshold: {
    global: {
      statements: 10,
      branches: 9,
      functions: 10,
      lines: 10,
    },
  },
  testPathIgnorePatterns: ['/node_modules/', '/e2e/'],
};
